name: Package and Upload to Cloudflare R2

on:
  push:
    branches:
      - main  # 触发动作的分支，可以根据需求调整
  workflow_run:
    workflows: ["Sync MaaResource Repository"] # 指定触发该工作流的上一个工作流名称
    types:
      - completed
  workflow_dispatch:

jobs:
  package_and_upload:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Get the current time
        id: get_time
        run: echo "CURRENT_TIME=$(date +'%Y%m%d%H%M%S')" >> $GITHUB_ENV
        
      - name: Create a ZIP file
        run: |
          zip -r latest.zip resource cache
      
      - name: Create a Version json
        run: |
          echo "{\"version\": \"$CURRENT_TIME\"}" > latest.json

      - name: Move ZIP and json file
        run: |
          mkdir ZIP
          mv latest.zip ZIP/
          mv latest.json ZIP/
          
      - name: Upload to Cloudflare R2
        uses: ryand56/r2-upload-action@latest # Can be any release
        with:
          r2-account-id: ${{ secrets.R2_ACCOUNT_ID }}
          r2-access-key-id: ${{ secrets.R2_ACCESS_KEY_ID }}
          r2-secret-access-key: ${{ secrets.R2_SECRET_ACCESS_KEY }}
          r2-bucket: ${{ secrets.R2_BUCKET }}
          source-dir: /home/runner/work/MaaResource/MaaResource/ZIP
          destination-dir: ./ # Can be anything as long as it is an actual path
          output-file-url: 'false' # defaults to true
          multipart-size: 100 # If the file size is greater than the value provided here, then use multipart upload
          max-retries: 5 # The maximum number of retries it takes to upload a multipart chunk until it moves on to the next part
          multipart-concurrent: false # Whether to concurrently upload a multipart chunk
          keep-file-fresh: 'true' # defaults to false
