name: Sync MaaResource Repository

on:
  schedule:
    - cron: '0 * * * *' # 每小时执行一次
  workflow_dispatch: # 允许手动触发

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout your repository
      uses: actions/checkout@v3

    - name: Clone MaaResource repository to temporary directory
      run: |
        git clone --depth 1 https://github.com/MaaAssistantArknights/MaaResource.git MaaResourceTemp
        rsync -avh MaaResourceTemp/ MaaResource/ --exclude .git

    - name: Sync content to your repository
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git add .
        git commit -m "Sync MaaResource repository" || echo "No changes to commit"
        git push origin HEAD
